name: met_to_eco_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26
  - pandas=2.2
  - matplotlib=3.10
  - seaborn
  - scikit-learn
  - scipy
  - jupyterlab
  - pip
  - pip:
    - cobra==0.29.1
    - efmlrs==2.3.6
    - memote==0.17.0
    - lmfit
    - upsetplot